### ISSUE TITLE
devServer 在热更新语法错误时不要退出  

### ISSUE THREAD

**Issue by wssgcg1213** [ice-lab/ice-next#525]
devServer 在热更新语法错误时不要退出  

复现方式：在任意文件中输入 JS Stynax 错误的文本并保存

```
TypeError: Cannot read properties of undefined (reading 'error')
    at transform (file:///Users/zhuoling/workspace/psolution-pro/node_modules/.pnpm/@ice+webpack-config@1.0.0-rc.2_djps47crhzxm6yv2aeusdnwrae/node_modules/@ice/webpack-config/esm/unPlugins/compilation.js:89:22)
    at async Object.compilationLoader (/Users/zhuoling/workspace/psolution-pro/node_modules/.pnpm/@ice+webpack-config@1.0.0-rc.2_djps47crhzxm6yv2aeusdnwrae/node_modules/@ice/webpack-config/esm/webpackLoaders/compilationLoader.cjs:5:20)
➜
```

**Comment by luhc228** [comment]
关联 https://github.com/ice-lab/ice-next/issues/509
